### ISSUE TITLE
ZIP64 extensions error

### ISSUE THREAD

**Issue by ExtReMLapin** [OpenScanEu/OpenScan#5]
I remember having this error in before but it wasn't (somehow) causing any issue : 

```txt
Dec  1 14:42:16 OpenScanPi Node-RED[269]: 1 Dec 14:42:16 - [error] [python3-function:Run Routine] Traceback (most recent call last):
Dec  1 14:42:16 OpenScanPi Node-RED[269]:   File "<string>", line 269, in <module>
Dec  1 14:42:16 OpenScanPi Node-RED[269]: 1 Dec 14:42:16 - [error] [python3-function:Run Routine]   File "<string>", line 248, in python_function
Dec  1 14:42:16 OpenScanPi Node-RED[269]:   File "<string>", line 166, in zip
Dec  1 14:42:16 OpenScanPi Node-RED[269]:   File "/usr/lib/python2.7/zipfile.py", line 824, in __exit__
Dec  1 14:42:16 OpenScanPi Node-RED[269]: 1 Dec 14:42:16 - [error] [python3-function:Run Routine]     self.close()
Dec  1 14:42:16 OpenScanPi Node-RED[269]:   File "/usr/lib/python2.7/zipfile.py", line 1371, in close
Dec  1 14:42:16 OpenScanPi Node-RED[269]: 1 Dec 14:42:16 - [error] [python3-function:Run Routine]     " would require ZIP64 extensions")
Dec  1 14:42:16 OpenScanPi Node-RED[269]: zipfile.LargeZipFile: Central directory offset would require ZIP64 extensions
Dec  1 14:42:16 OpenScanPi Node-RED[269]: 1 Dec 14:42:16 - [error] [python3-function:Run Routine] Python Function process exited with code 1
Dec  1 14:42:16 OpenScanPi Node-RED[269]: 1 Dec 14:42:16 - [info] [python3-function:Run Routine] Python function 'Run Routine' running on PID 3146
```

I fixed it by going into ***Run Routine*** module on scan tab

![](https://i.imgur.com/eaAsfuh.png)

line 101

```python
    with ZipFile("/home/pi/shared/temp.zip", "a", allowZip64=True) as zip:
```

to

```python
    with ZipFile("/home/pi/shared/temp.zip", "a") as zip:
```

**Comment by ExtReMLapin** [comment]
There might be a reason it tried to make a > 2^64 bits file.

It tried to generate a file for some reason with all the unreferenced pictures in it.
The archive weights ~2gb but only "contains 4 pics"

![](https://i.imgur.com/1iUxfc0.png)
![](https://i.imgur.com/gBT0oqe.png)

But when you open it with 7zip, it shows much more files : 

![](https://i.imgur.com/YzMhsf9.png)
